

services:

  pipeline:
    build:
      context: .
      dockerfile: docker/pipeline.Dockerfile
    container_name: qa-pipeline
    volumes:
      - ./data:/app/data
      - ./mlruns:/app/mlruns
      - ./src/models:/app/src/models
    command: python run_pipeline.py

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: qa-api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./mlruns:/app/mlruns
      - ./src/models:/app/src/models
    depends_on:
      - pipeline