apiVersion: v1
kind: ConfigMap
metadata:
  name: qa-log-anomaly-config
  namespace: qa-log-anomaly-detector
  labels:
    app.kubernetes.io/part-of: qa-log-anomaly-detector
data:
  MLFLOW_TRACKING_URI: http://mlflow.qa-log-anomaly-detector.svc.cluster.local:5000
  MLFLOW_MODEL_URI: models:/qa-log-anomaly-detector@production
  MLFLOW_BACKEND_STORE_URI: sqlite:////data/mlflow.db
  MLFLOW_ARTIFACT_ROOT: /data/mlruns
