apiVersion: v1
kind: Service
metadata:
  name: qa-log-anomaly-api
  namespace: qa-log-anomaly-detector
  labels:
    app.kubernetes.io/name: qa-log-anomaly-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: qa-log-anomaly-api
  ports:
    - name: http
      port: 80
      targetPort: http
