FROM python:3.10

RUN pip install --no-cache-dir mlflow boto3 psycopg2-binary

WORKDIR /mlflow

EXPOSE 5000

CMD mlflow server \
    --host 0.0.0.0 \
    --port 5000 \
    --allowed-hosts "*" \
    --backend-store-uri "${MLFLOW_BACKEND_STORE_URI:-sqlite:////mlflow/mlflow.db}" \
    --default-artifact-root "${MLFLOW_ARTIFACT_ROOT:-/mlruns}"
