name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-and-build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Build pipeline image
        run: docker build -f docker/pipeline.Dockerfile -t qa-pipeline .

      - name: Run pipeline container
        run: docker run qa-pipeline
      
      - name: Run pipeline locally for tests
        run: python run_pipeline.py
       

      - name: Run tests
        run: pytest

      - name: Build Pipeline Image
        run: docker build -f docker/pipeline.Dockerfile -t qa-pipeline .

      - name: Build API Image
        run: docker build -f docker/Dockerfile.api -t qa-api .